"""
Beacon v0.7 — Page Service gRPC Server

Implements PageService as defined in proto/page/v1/page.proto.
Runs as a standalone process on port 50051, using the Django ORM
for database access.

This is the first service extracted from the monolith using the
Strangler Fig pattern (Chapter 7, Section 7.7). The page service
handles all CRUD operations for Pages and PageLinks.

Architecture:
    gRPC clients (search-service, notify-service, collab-service)
    ──► page-service:50051
          │
          ├── Django ORM
          │     ├── shard-0 (organizations hashed here)
          │     ├── shard-1
          │     ├── shard-2
          │     └── shard-3
          │
          └── AuthInterceptor (HMAC-signed tokens)
"""

import logging
import os
import sys
import time
from concurrent import futures

import grpc

# Ensure Django settings are available before importing models.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "beacon.settings")

import django
django.setup()

from django.conf import settings
from django.core.paginator import Paginator
from django.db.models import Q

from core.models import Page, PageLink

# Generated protobuf stubs — these are generated by grpcio-tools:
#   python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. proto/page/v1/page.proto
try:
    import proto.page.v1.page_pb2 as page_pb2
    import proto.page.v1.page_pb2_grpc as page_pb2_grpc
except ImportError:
    # Fallback: use a simulated stub for development without code generation.
    page_pb2 = None
    page_pb2_grpc = None

from auth_interceptor import AuthInterceptor, create_service_token

logger = logging.getLogger("beacon.page_service")


class PageServiceServicer(page_pb2_grpc.PageServiceServicer if page_pb2_grpc else object):
    """
    gRPC servicer implementing the PageService contract.

    Each method:
    1. Validates the request (checking that organization_id is present).
    2. Performs the database operation via Django ORM.
    3. Returns a protobuf response.
    """

    # ── GetPage ───────────────────────────────────────────────────

    def GetPage(self, request, context):
        """Fetch a single page by organization_id and slug."""
        try:
            page = Page.objects.get(
                organization_id=request.organization_id,
                slug=request.slug,
            )
            return page_pb2.GetPageResponse(page=_page_to_proto(page))
        except Page.DoesNotExist:
            context.abort(grpc.StatusCode.NOT_FOUND, "page not found")

    # ── ListPages ─────────────────────────────────────────────────

    def ListPages(self, request, context):
        """List pages within an organization with cursor-based pagination."""
        page_size = min(request.page_size or 20, 100)
        order_by = request.order_by or "-updated_at"

        queryset = (
            Page.objects
            .filter(organization_id=request.organization_id)
            .select_related("author")
            .only("title", "slug", "organization_id", "author",
                  "updated_at", "incoming_count", "outgoing_count")
            .order_by(order_by)
        )

        # Cursor-based pagination: page_token is the last page's updated_at ISO.
        if request.page_token:
            queryset = queryset.filter(updated_at__lt=request.page_token)

        paginator = Paginator(queryset, page_size)
        page_obj = paginator.page(1)

        pages = [_page_to_proto(p) for p in page_obj.object_list]
        next_token = ""
        if page_obj.has_next():
            # The cursor is the updated_at of the last item on this page.
            last_updated = page_obj.object_list[len(page_obj.object_list) - 1].updated_at
            next_token = last_updated.isoformat()

        return page_pb2.ListPagesResponse(
            pages=pages,
            next_page_token=next_token,
            total_count=paginator.count,
        )

    # ── CreatePage ────────────────────────────────────────────────

    def CreatePage(self, request, context):
        """Create a new page."""
        from django.contrib.auth import get_user_model
        User = get_user_model()

        try:
            author = User.objects.get(pk=request.author_id)
        except User.DoesNotExist:
            context.abort(grpc.StatusCode.INVALID_ARGUMENT, "author not found")

        page = Page.objects.create(
            organization_id=request.organization_id,
            title=request.title,
            body=request.body,
            author=author,
        )

        logger.info("Page created: org=%d slug=%s", page.organization_id, page.slug)
        return page_pb2.CreatePageResponse(page=_page_to_proto(page))

    # ── UpdatePage ────────────────────────────────────────────────

    def UpdatePage(self, request, context):
        """Update an existing page."""
        try:
            page = Page.objects.get(
                organization_id=request.organization_id,
                slug=request.slug,
            )
        except Page.DoesNotExist:
            context.abort(grpc.StatusCode.NOT_FOUND, "page not found")

        if request.title:
            page.title = request.title
        if request.body:
            page.body = request.body

        page.save()

        logger.info("Page updated: org=%d slug=%s", page.organization_id, page.slug)
        return page_pb2.UpdatePageResponse(page=_page_to_proto(page))

    # ── DeletePage ────────────────────────────────────────────────

    def DeletePage(self, request, context):
        """Delete a page."""
        try:
            page = Page.objects.get(
                organization_id=request.organization_id,
                slug=request.slug,
            )
            page.delete()
            logger.info("Page deleted: org=%d slug=%s",
                        request.organization_id, request.slug)
            return page_pb2.DeletePageResponse(success=True)
        except Page.DoesNotExist:
            context.abort(grpc.StatusCode.NOT_FOUND, "page not found")

    # ── SearchPages ───────────────────────────────────────────────

    def SearchPages(self, request, context):
        """Search pages within an organization by title or body content."""
        max_results = min(request.max_results or 20, 50)

        queryset = (
            Page.objects
            .filter(organization_id=request.organization_id)
            .filter(
                Q(title__icontains=request.query) |
                Q(body__icontains=request.query)
            )
            .only("title", "slug", "organization_id", "incoming_count",
                  "outgoing_count", "updated_at")
            .order_by("-incoming_count")[:max_results]
        )

        pages = [_page_to_proto(p) for p in queryset]
        total = Page.objects.filter(
            organization_id=request.organization_id
        ).filter(
            Q(title__icontains=request.query) |
            Q(body__icontains=request.query)
        ).count()

        return page_pb2.SearchPagesResponse(pages=pages, total_matches=total)


# ── Helper: Model → Proto ────────────────────────────────────────

def _page_to_proto(page) -> "page_pb2.Page":
    """Convert a Django Page model instance to a protobuf Page message."""
    return page_pb2.Page(
        id=page.pk,
        organization_id=page.organization_id,
        title=page.title,
        slug=page.slug,
        body=page.body or "",
        author_id=page.author_id,
        incoming_count=page.incoming_count,
        outgoing_count=page.outgoing_count,
        created_at=page.created_at.isoformat() if page.created_at else "",
        updated_at=page.updated_at.isoformat() if page.updated_at else "",
    )


# ── Server Entry Point ───────────────────────────────────────────

def serve():
    """Start the gRPC server on port 50051."""
    server = grpc.server(
        futures.ThreadPoolExecutor(max_workers=10),
        interceptors=[AuthInterceptor()],
    )

    if page_pb2_grpc:
        page_pb2_grpc.add_PageServiceServicer_to_server(
            PageServiceServicer(), server
        )

    port = "50051"
    server.add_insecure_port(f"[::]:{port}")
    server.start()

    logger.info("Page Service gRPC server listening on port %s", port)
    logger.info("Connected to databases: %s", list(settings.DATABASES.keys()))

    try:
        while True:
            time.sleep(86400)  # One day in seconds.
    except KeyboardInterrupt:
        logger.info("Shutting down Page Service...")
        server.stop(grace=5)


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    serve()
